"""Add number field to cards

Revision ID: 9e0370c5ef15
Revises: d42bd1037fc8
Create Date: 2025-06-04 23:47:02.046047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e0370c5ef15'
down_revision = 'd42bd1037fc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', sa.String(length=16), nullable=False))
        batch_op.add_column(sa.Column('exp_date', sa.String(length=5), nullable=False))
        batch_op.alter_column('cvv',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.String(length=3),
               existing_nullable=False)
        batch_op.drop_column('is_default')
        batch_op.drop_column('expiry')
        batch_op.drop_column('card_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_number', sa.VARCHAR(length=16), nullable=False))
        batch_op.add_column(sa.Column('expiry', sa.VARCHAR(length=7), nullable=False))
        batch_op.add_column(sa.Column('is_default', sa.BOOLEAN(), nullable=True))
        batch_op.alter_column('cvv',
               existing_type=sa.String(length=3),
               type_=sa.VARCHAR(length=4),
               existing_nullable=False)
        batch_op.drop_column('exp_date')
        batch_op.drop_column('number')

    # ### end Alembic commands ###
