"""add cards

Revision ID: d42bd1037fc8
Revises: 7ac1a34af091
Create Date: 2025-06-04 23:29:19.733596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd42bd1037fc8'
down_revision = '7ac1a34af091'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_phone', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('number', sa.String(length=16), nullable=False))
        batch_op.add_column(sa.Column('exp_date', sa.String(length=7), nullable=False))
        batch_op.create_unique_constraint('uq_user_card', ['user_phone', 'number'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('card_number')
        batch_op.drop_column('expiry')
        batch_op.drop_column('is_default')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_default', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('expiry', sa.VARCHAR(length=7), nullable=False))
        batch_op.add_column(sa.Column('card_number', sa.VARCHAR(length=16), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_constraint('uq_user_card', type_='unique')
        batch_op.drop_column('exp_date')
        batch_op.drop_column('number')
        batch_op.drop_column('user_phone')

    # ### end Alembic commands ###
